<?php
function custom_post_types() {
    // Register Banner Post Type
    $labels = array(
        'name'                  => _x( 'Banners', 'Post Type General Name', 'enjoy' ),
        'singular_name'         => _x( 'Banner', 'Post Type Singular Name', 'enjoy' ),
        'menu_name'             => __( 'Банери на головну', 'enjoy' ),
        'name_admin_bar'        => __( 'Banner', 'enjoy' ),
        'archives'              => __( 'Banner Archives', 'enjoy' ),
        'attributes'            => __( 'Banner Attributes', 'enjoy' ),
        'parent_item_colon'     => __( 'Parent Banner:', 'bamboo' ),
        'all_items'             => __( 'All Banners', 'bamboo' ),
        'add_new_item'          => __( 'Add New Banner', 'bamboo' ),
        'add_new'               => __( 'Add New', 'bamboo' ),
        'new_item'              => __( 'New Banner', 'bamboo' ),
        'edit_item'             => __( 'Edit Banner', 'bamboo' ),
        'update_item'           => __( 'Update Banner', 'bamboo' ),
        'view_item'             => __( 'View Banner', 'bamboo' ),
        'view_items'            => __( 'View Banners', 'bamboo' ),
        'search_items'          => __( 'Search Banner', 'bamboo' ),
        'not_found'             => __( 'Not found', 'bamboo' ),
        'not_found_in_trash'    => __( 'Not found in Trash', 'bamboo' ),
        'featured_image'        => __( 'Featured Image', 'bamboo' ),
        'set_featured_image'    => __( 'Set featured image', 'bamboo' ),
        'remove_featured_image' => __( 'Remove featured image', 'bamboo' ),
        'use_featured_image'    => __( 'Use as featured image', 'bamboo' ),
        'insert_into_item'      => __( 'Insert into banner', 'bamboo' ),
        'uploaded_to_this_item' => __( 'Uploaded to this banner', 'bamboo' ),
        'items_list'            => __( 'Banners list', 'bamboo' ),
        'items_list_navigation' => __( 'Banners list navigation', 'bamboo' ),
        'filter_items_list'     => __( 'Filter banners list', 'bamboo' ),
    );
    $args = array(
        'label'                 => __( 'Banner', 'bamboo' ),
        'description'           => __( 'Banner Description', 'bamboo' ),
        'labels'                => $labels,
        'supports'              => array( 'title', 'editor', 'thumbnail' ),
        //'taxonomies'            => array( 'category', 'post_tag' ),
        'hierarchical'          => false,
        'public'                => true,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 5,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => true,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
    );
    register_post_type( 'banner', $args );

    // Register Reviews Post Type
    /*$labels = array(
        'name'                  => _x( 'Reviews', 'Post Type General Name', 'bamboo' ),
        'singular_name'         => _x( 'Review', 'Post Type Singular Name', 'bamboo' ),
        'menu_name'             => __( 'Reviews', 'bamboo' ),
        'name_admin_bar'        => __( 'Review', 'bamboo' ),
        'archives'              => __( 'Review Archives', 'bamboo' ),
        'attributes'            => __( 'Review Attributes', 'bamboo' ),
        'parent_item_colon'     => __( 'Parent Review:', 'bamboo' ),
        'all_items'             => __( 'All Reviews', 'bamboo' ),
        'add_new_item'          => __( 'Add New Review', 'bamboo' ),
        'add_new'               => __( 'Add New', 'bamboo' ),
        'new_item'              => __( 'New Review', 'bamboo' ),
        'edit_item'             => __( 'Edit Review', 'bamboo' ),
        'update_item'           => __( 'Update Review', 'bamboo' ),
        'view_item'             => __( 'View Review', 'bamboo' ),
        'view_items'            => __( 'View Reviews', 'bamboo' ),
        'search_items'          => __( 'Search Review', 'bamboo' ),
        'not_found'             => __( 'Not found', 'bamboo' ),
        'not_found_in_trash'    => __( 'Not found in Trash', 'bamboo' ),
        'featured_image'        => __( 'Featured Image', 'bamboo' ),
        'set_featured_image'    => __( 'Set featured image', 'bamboo' ),
        'remove_featured_image' => __( 'Remove featured image', 'bamboo' ),
        'use_featured_image'    => __( 'Use as featured image', 'bamboo' ),
        'insert_into_item'      => __( 'Insert into review', 'bamboo' ),
        'uploaded_to_this_item' => __( 'Uploaded to this review', 'bamboo' ),
        'items_list'            => __( 'Reviews list', 'bamboo' ),
        'items_list_navigation' => __( 'Reviews list navigation', 'bamboo' ),
        'filter_items_list'     => __( 'Filter reviews list', 'bamboo' ),
    );
    $args = array(
        'label'                 => __( 'Review', 'bamboo' ),
        'description'           => __( 'Review Description', 'bamboo' ),
        'labels'                => $labels,
        'supports'              => array( 'title', 'editor', 'comments', 'thumbnail' ),
        'taxonomies'            => array( 'category', 'post_tag' ),
        'hierarchical'          => false,
        'public'                => true,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 5,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => true,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
    );
    register_post_type( 'reviews', $args );*/
}
add_action( 'init', 'custom_post_types', 0 );